export const baseURL = 'http://localhost:4000/api/v1'
export const rootURL = 'http://localhost:4000'
export const pakistanCities = [
    "Abbottabad",
    "Attock",
    "Badin",
    "Bahawalnagar",
    "Bahawalpur",
    "Bannu",
    "Bhakkar",
    "Burewala",
    "Chakwal",
    "Charsadda",
    "Chiniot",
    "Dadu",
    "Daska",
    "Dera Ghazi Khan",
    "Dera Ismail Khan",
    "Faisalabad",
    "Ghotki",
    "Gujar Khan",
    "Gujranwala",
    "Gujrat",
    "Hafizabad",
    "Haripur",
    "Hyderabad",
    "Islamabad",
    "Jacobabad",
    "Jhang",
    "Jhelum",
    "Kamoke",
    "Karachi",
    "Kasur",
    "Khairpur",
    "Khanewal",
    "Khuzdar",
    "Kohat",
    "Lahore",
    "Larkana",
    "Mandi Bahauddin",
    "Mardan",
    "Mianwali",
    "Mirpur",
    "Mirpur Khas",
    "Multan",
    "Muridke",
    "Muzaffarabad",
    "Muzaffargarh",
    "Nankana Sahib",
    "Narowal",
    "Nawabshah",
    "Nowshera",
    "Okara",
    "Pakpattan",
    "Peshawar",
    "Quetta",
    "Rahim Yar Khan",
    "Rawalpindi",
    "Sadiqabad",
    "Sahiwal",
    "Sargodha",
    "Sheikhupura",
    "Shikarpur",
    "Sialkot",
    "Sukkur",
    "Swabi",
    "Tando Adam",
    "Tando Allahyar",
    "Vehari",
    "Wah Cantonment",
  ];
  