export const baseURL = 'http://localhost:4000/api/v1'
// export const baseURL = 'https://growcrm.glitch.me/api/v1'
export const rootURL = 'http://localhost:4000'
// export const rootURL = 'https://growcrm.glitch.me'
export const pakistanCities = [
  "Abbottabad",
  "Adilpur",
  "Ahmadpur East",
  "Ahmadpur Sial",
  "Akora",
  "Aliabad",
  "Alik Ghund",
  "Alipur",
  "Alizai",
  "Alpurai",
  "Aman Garh",
  "Amirabad",
  "Arifwala",
  "Ashanagro Koto",
  "Athmuqam",
  "Attock City",
  "Awaran",
  "Baddomalhi",
  "Badin",
  "Bagarji",
  "Bagh",
  "Bahawalnagar",
  "Bahawalnagar",
  "Bahawalpur",
  "Bakhri Ahmad Khan",
  "Bandhi",
  "Bannu",
  "Barishal",
  "Barkhan",
  "Basirpur",
  "Basti Dosa",
  "Bat Khela",
  "Battagram",
  "Begowala",
  "Bela",
  "Berani",
  "Bhag",
  "Bhakkar",
  "Bhalwal",
  "Bhan",
  "Bhawana",
  "Bhera",
  "Bhimbar",
  "Bhiria",
  "Bhit Shah",
  "Bhopalwala",
  "Bozdar Wada",
  "Chakwal",
  "Chaman",
  "Chamber",
  "Charsadda",
  "Chawinda",
  "Chenab Nagar",
  "Cherat Cantonement",
  "Chhor",
  "Chichawatni",
  "Chilas",
  "Chiniot",
  "Chishtian",
  "Chitral",
  "Choa Saidan Shah",
  "Chowki Jamali",
  "Chuchar-kana Mandi",
  "Chunian",
  "Dadhar",
  "Dadu",
  "Daggar",
  "Daira Din Panah",
  "Dajal",
  "Dalbandin",
  "Dandot RS",
  "Daromehar",
  "Darya Khan",
  "Darya Khan Marri",
  "Daska Kalan",
  "Dasu",
  "Daud Khel",
  "Daulatpur",
  "Daultala",
  "Daur",
  "Dera Allahyar",
  "Dera Bugti",
  "Dera Ghazi Khan",
  "Dera Ismail Khan",
  "Dera Murad Jamali",
  "Dhanot",
  "Dhaunkal",
  "Dhoro Naro",
  "Digri",
  "Dijkot",
  "Dinan Bashnoian Wala",
  "Dinga",
  "Dipalpur",
  "Diplo",
  "Doaba",
  "Dokri",
  "Duki",
  "Dullewala",
  "Dunga Bunga",
  "Dunyapur",
  "Eidgah",
  "Eminabad",
  "Faisalabad",
  "Faqirwali",
  "Faruka",
  "Fazilpur",
  "Fort Abbas",
  "Gadani",
  "Gakuch",
  "Gambat",
  "Gandava",
  "Garh Maharaja",
  "Garhi Khairo",
  "Garhiyasin",
  "Gharo",
  "Ghauspur",
  "Ghotki",
  "Gilgit",
  "Gojra",
  "Goth Garelo",
  "Goth Phulji",
  "Goth Radhan",
  "Gujar Khan",
  "Gujranwala",
  "Gujrat",
  "Gulishah Kach",
  "Gwadar",
  "Hadali",
  "Hafizabad",
  "Hala",
  "Hangu",
  "Haripur",
  "Harnai",
  "Harnoli",
  "Harunabad",
  "Hasilpur",
  "Hattian Bala",
  "Haveli Lakha",
  "Havelian",
  "Hazro City",
  "Hingorja",
  "Hujra Shah Muqim",
  "Hyderabad",
  "Islamabad",
  "Islamkot",
  "Jacobabad",
  "Jahanian Shah",
  "Jalalpur Jattan",
  "Jalalpur Pirwala",
  "Jampur",
  "Jamshoro",
  "Jand",
  "Jandiala Sher Khan",
  "Jaranwala",
  "Jati",
  "Jatoi Shimali",
  "Jauharabad",
  "Jhang City",
  "Jhang Sadr",
  "Jhawarian",
  "Jhelum",
  "Jhol",
  "Jiwani",
  "Johi",
  "Jām Sāhib",
  "Kabirwala",
  "Kadhan",
  "Kahna Nau",
  "Kahror Pakka",
  "Kahuta",
  "Kakad Wari Dir Upper",
  "Kalabagh",
  "Kalaswala",
  "Kalat",
  "Kaleke Mandi",
  "Kallar Kahar",
  "Kalur Kot",
  "Kamalia",
  "Kamar Mushani",
  "Kambar",
  "Kamoke",
  "Kamra",
  "Kandhkot",
  "Kandiari",
  "Kandiaro",
  "Kanganpur",
  "Karachi",
  "Karak",
  "Karaundi",
  "Kario Ghanwar",
  "Karor",
  "Kashmor",
  "Kasur",
  "Keshupur",
  "Khadan Khak",
  "Khadro",
  "Khairpur",
  "Khairpur Mir’s",
  "Khairpur Nathan Shah",
  "Khairpur Tamewah",
  "Khalabat",
  "Khandowa",
  "Khanewal",
  "Khangah Dogran",
  "Khangarh",
  "Khanpur",
  "Khanpur Mahar",
  "Kharan",
  "Kharian",
  "Khewra",
  "Khurrianwala",
  "Khushāb",
  "Khuzdar",
  "Kohat",
  "Kohlu",
  "Kot Addu",
  "Kot Diji",
  "Kot Ghulam Muhammad",
  "Kot Malik Barkhurdar",
  "Kot Mumin",
  "Kot Radha Kishan",
  "Kot Rajkour",
  "Kot Samaba",
  "Kot Sultan",
  "Kotli",
  "Kotli Loharan",
  "Kotri",
  "Kulachi",
  "Kundian",
  "Kunjah",
  "Kunri",
  "Lachi",
  "Ladhewala Waraich",
  "Lahore",
  "Lakki",
  "Lala Musa",
  "Lalian",
  "Landi Kotal",
  "Larkana",
  "Layyah",
  "Liliani",
  "Lodhran",
  "Loralai",
  "Mach",
  "Madeji",
  "Mailsi",
  "Malakand",
  "Malakwal",
  "Malakwal City",
  "Malir Cantonment",
  "Mamu Kanjan",
  "Mananwala",
  "Mandi Bahauddin",
  "Mangla",
  "Mankera",
  "Mansehra",
  "Mardan",
  "Mastung",
  "Matiari",
  "Matli",
  "Mehar",
  "Mehmand Chak",
  "Mehrabpur",
  "Mian Channun",
  "Mianke Mor",
  "Mianwali",
  "Minchianabad",
  "Mingora",
  "Miran Shah",
  "Miro Khan",
  "Mirpur Bhtoro",
  "Mirpur Khas",
  "Mirpur Mathelo",
  "Mirpur Sakro",
  "Mirwah Gorchani",
  "Mitha Tiwana",
  "Mithi",
  "Moro",
  "Moza Shahwala",
  "Multan",
  "Muridke",
  "Murree",
  "Musa Khel Bazar",
  "Mustafābād",
  "Muzaffargarh",
  "Muzaffarābād",
  "Nabisar",
  "Nankana Sahib",
  "Narang Mandi",
  "Narowal",
  "Nasirabad",
  "Naudero",
  "Naukot",
  "Naushahra Virkan",
  "Naushahro Firoz",
  "Nawabshah",
  "Nazir Town",
  "New Bādāh",
  "New Mirpur",
  "Noorabad",
  "Nowshera",
  "Nowshera Cantonment",
  "Nushki",
  "Okara",
  "Ormara",
  "Pabbi",
  "Pad Idan",
  "Paharpur",
  "Pakpattan",
  "Panjgur",
  "Pano Aqil",
  "Parachinar",
  "Pasni",
  "Pasrur",
  "Pattoki",
  "Peshawar",
  "Pind Dadan Khan",
  "Pindi Bhattian",
  "Pindi Gheb",
  "Pir Jo Goth",
  "Pir Mahal",
  "Pishin",
  "Pithoro",
  "Qadirpur Ran",
  "Qila Abdullah",
  "Qila Saifullah",
  "Quetta",
  "Rahim Yar Khan",
  "Raiwind",
  "Raja Jang",
  "Rajanpur",
  "Rajo Khanani",
  "Ranipur",
  "Rasulnagar",
  "Ratodero",
  "Rawala Kot",
  "Rawalpindi",
  "Renala Khurd",
  "Risalpur Cantonment",
  "Rohri",
  "Rojhan",
  "Rustam",
  "Saddiqabad",
  "Sahiwal",
  "Sahiwal",
  "Saidu Sharif",
  "Sakrand",
  "Samaro",
  "Sambrial",
  "Sanghar",
  "Sangla Hill",
  "Sanjwal",
  "Sann",
  "Sarai Alamgir",
  "Sarai Naurang",
  "Sarai Sidhu",
  "Sargodha",
  "Sehwan",
  "Setharja Old",
  "Shabqadar",
  "Shahdad Kot",
  "Shahdadpur",
  "Shahkot",
  "Shahpur",
  "Shahpur Chakar",
  "Shahr Sultan",
  "Shakargarh",
  "Sharqpur Sharif",
  "Shekhupura",
  "Shikarpur",
  "Shingli Bala",
  "Shinpokh",
  "Shorkot",
  "Shujaabad",
  "Sialkot",
  "Sibi",
  "Sillanwali",
  "Sinjhoro",
  "Skardu",
  "Sobhodero",
  "Sodhri",
  "Sohbatpur",
  "Sukheke Mandi",
  "Sukkur",
  "Surab",
  "Surkhpur",
  "Swabi",
  "Sīta Road",
  "Talagang",
  "Talamba",
  "Talhar",
  "Tandlianwala",
  "Tando Adam",
  "Tando Allahyar",
  "Tando Bago",
  "Tando Jam",
  "Tando Mitha Khan",
  "Tando Muhammad Khan",
  "Tangi",
  "Tangwani",
  "Tank",
  "Taunsa",
  "Thal",
  "Tharu Shah",
  "Thatta",
  "Thul",
  "Timargara",
  "Toba Tek Singh",
  "Topi",
  "Turbat",
  "Ubauro",
  "Umarkot",
  "Upper Dir",
  "Usta Muhammad",
  "Uthal",
  "Utmanzai",
  "Vihari",
  "Wana",
  "Warah",
  "Wazirabad",
  "Yazman",
  "Zafarwal",
  "Zahir Pir",
  "Zaida",
  "Zhob",
  "Ziarat",
];
